ALTER TABLE orders
  ADD COLUMN cgst_rate DECIMAL(5,2) NOT NULL DEFAULT 14 AFTER tax_amount,
  ADD COLUMN sgst_rate DECIMAL(5,2) NOT NULL DEFAULT 14 AFTER cgst_rate,
  ADD COLUMN tax_rate DECIMAL(5,2) NOT NULL DEFAULT 28 AFTER sgst_rate;
